# Generated by Django 4.0.10 on 2024-03-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nick_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
