# Generated by Django 4.0.10 on 2024-03-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
