# Generated by Django 4.0.10 on 2024-03-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_person_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nick_name',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
