version: '3'

networks:
  nw:
    driver: bridge

services:
  backend:
    container_name: backendbi
    build: ./pingpong
    command: python manage.py runserver localhost:3030
    volumes:
      - ./backend:/code
    ports:
      - "3030:3030"
    networks:
      - nw
  nginx:
    build: ./frontend
    container_name: frontendbi
    ports:
      - "54:54"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - nw
  db:
    build: ./postgres
    container_name: dbi
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5431"
    networks:
      - nw

volumes:
  postgres_data: