version: '3'

networks:
  nw:
    driver: bridge
  nw2:
    driver: bridge

services:

  user:
    container_name: user
    build: ./user
    volumes:
      - ./user:/app
    ports:
      - "8080:8080"
    networks:
      - nw
  db_user:
    container_name: db_user
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - user_data:/var/lib/postgresql/data
      - ./user/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - nw
      - nw2


  pinpong:
    container_name: pingpong
    build: ./pingpong
    command: python3 manage.py runserver 0.0.0.0:8081
    volumes:
      - ./pingpong:/app
    ports:
      - "8081:8081"
    networks:
      - nw2
  db_backend:
    container_name: db_backend
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pingpong_data:/var/lib/postgresql/data
      - ./user/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - nw2

  nginx:
    build: ./frontend
    container_name: frontendbi
    ports:
      - "8082:8082"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html/
    depends_on:
      - user
    networks:
      - nw

volumes:
  user_data:
  pingpong_data:

  