version: '3'

networks:
  nw:
    driver: bridge

services:
  backend:
    container_name: backendbi
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8081
    volumes:
      - ./backend:/code
    ports:
      - "8081:8081"
    networks:
      - nw
  nginx:
    build: ./client
    container_name: frontendbi
    ports:
      - "8082:8082"
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client:/usr/share/nginx/html/  # Bu satırı ekledik
    depends_on:
      - backend
    networks:
      - nw
  db:
    build: ./postgres
    container_name: dbi
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8083:8083"
    networks:
      - nw

volumes:
  postgres_data: