# Generated by Django 4.0.10 on 2024-06-18 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_games', models.IntegerField(default=1)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('new_field', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stats2',
            },
        ),
    ]
