# Generated by Django 4.0.10 on 2024-06-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stats',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
