# Generated by Django 4.0.10 on 2024-06-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/default-avatar-profile-icon-social-600nw-1677509740.jpg', null=True),
        ),
    ]
