# Generated by Django 4.0.10 on 2024-06-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_verificationcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='user_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
