# Generated by Django 4.0.10 on 2024-07-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
