# Generated by Django 4.0.10 on 2024-06-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_verificationcode_user_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='user',
        ),
    ]
