# Generated by Django 4.0.10 on 2024-07-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='max_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
