# Generated by Django 4.0.10 on 2024-07-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_post_location_post_max_people_post_reward_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reward',
        ),
    ]
