# Generated by Django 4.0.10 on 2024-07-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_post_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applicants',
            field=models.JSONField(default=list),
        ),
    ]
