# Generated by Django 4.0.10 on 2024-06-23 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_x', models.IntegerField(default=0.0)),
                ('_y', models.IntegerField(default=0.0)),
                ('_radius', models.FloatField(default=0.0)),
                ('Rx', models.FloatField(default=0.0)),
                ('Ry', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Paddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_x', models.FloatField(default=0.0)),
                ('_y', models.FloatField(default=0.0)),
                ('_radius', models.FloatField(default=0.0)),
                ('end', models.FloatField(default=0.0)),
                ('Rx', models.FloatField(default=0.0)),
                ('Ry', models.FloatField(default=0.0)),
                ('Rradius', models.FloatField(default=0.0)),
                ('Rend', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_width', models.FloatField()),
                ('_height', models.FloatField()),
                ('_ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftPlyrScore', models.IntegerField(default=0)),
                ('rightPlyrScore', models.IntegerField(default=0)),
                ('maxScore', models.IntegerField(default=5)),
                ('dirX', models.FloatField(default=2.0)),
                ('dirY', models.FloatField(default=0.0)),
                ('speedBall', models.FloatField(default=10.0)),
                ('speedPlayer', models.FloatField(default=30.0)),
                ('beginPos', models.BooleanField(default=True)),
                ('animationFlag', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
                ('ball', models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, to='pingpong.ball')),
                ('leftPaddle', models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, related_name='left_games', to='pingpong.paddle')),
                ('rightPaddle', models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, related_name='right_games', to='pingpong.paddle')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingpong.screen')),
            ],
        ),
    ]
