# Generated by Django 4.0.10 on 2024-06-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='players',
            field=models.IntegerField(default=0),
        ),
    ]
