# Generated by Django 4.0.10 on 2024-06-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0002_rooms_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='game',
            name='leftPaddle',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rightPaddle',
        ),
        migrations.RemoveField(
            model_name='game',
            name='screen',
        ),
        migrations.DeleteModel(
            name='Ball',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Paddle',
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
    ]
