# Generated by Django 4.0.10 on 2024-07-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0003_remove_game_ball_remove_game_leftpaddle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='player1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rooms',
            name='player2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
