# Generated by Django 4.0.10 on 2024-07-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0004_rooms_player1_rooms_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='player1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='player2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
    ]
