CREATE DATABASE user_db;
CREATE USER root WITH PASSWORD 'mysecretpassword';

-- create user table

GRANT ALL PRIVILEGES ON DATABASE user_db TO user1;
ALTER ROLE user1 WITH SUPERUSER;
ALTER ROLE user1 WITH CREATEROLE;